#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="$ROOT_DIR/.venv"

log() {
    printf '\n========== %s ==========\n' "$1"
}

run_as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        echo "ERROR: 需要 root 或 sudo 权限执行：$*" >&2
        exit 1
    fi
}

cd "$ROOT_DIR"

log "安装系统依赖"

if command -v apt-get >/dev/null 2>&1; then
    run_as_root apt-get update

    run_as_root apt-get install -y \
        python3 \
        python3-venv \
        python3-dev \
        build-essential \
        g++ \
        libpq-dev \
        postgresql-client \
        redis-tools \
        default-mysql-client \
        openssh-client \
        curl \
        git
else
    echo "ERROR: 当前脚本只支持 Debian/Ubuntu apt 环境" >&2
    exit 1
fi

log "创建 Python 虚拟环境"

if [ ! -x "$VENV_DIR/bin/python" ]; then
    python3 -m venv "$VENV_DIR"
fi

PYTHON="$VENV_DIR/bin/python"
PIP="$VENV_DIR/bin/pip"

"$PIP" install --upgrade pip setuptools wheel

log "安装 CPU-only PyTorch"

if "$PYTHON" -c \
    'import torch; assert torch.version.cuda is None' \
    >/dev/null 2>&1
then
    echo "[OK] CPU-only PyTorch 已安装"
else
    "$PIP" uninstall -y \
        torch \
        torchvision \
        torchaudio \
        triton \
        2>/dev/null || true

    "$PIP" install \
        --index-url https://download.pytorch.org/whl/cpu \
        torch
fi

log "安装项目 Python 依赖"

"$PIP" install -r "$ROOT_DIR/requirements.txt"

"$PYTHON" - <<'PY'
import torch

if torch.version.cuda is not None:
    raise SystemExit(
        f"ERROR: 当前不是 CPU-only PyTorch: {torch.__version__}"
    )

print("torch_version:", torch.__version__)
print("torch_cuda:", torch.version.cuda)
print("[OK] CPU-only PyTorch")
PY

log "编译 C++ 扩展"

(
    cd "$ROOT_DIR/cpp_core"
    "$PYTHON" setup.py build_ext --inplace --force
)

PYTHONPATH="$ROOT_DIR/cpp_core" "$PYTHON" - <<'PY'
import todo_core

engine = todo_core.TodoEngine()

required_methods = [
    "add_todo",
    "upsert_todo",
    "remove_todo",
    "clear",
    "search",
    "size",
]

for method in required_methods:
    if not hasattr(engine, method):
        raise SystemExit(f"ERROR: C++ 缺少接口 {method}")

print("[OK] C++ extension")
PY

log "准备环境配置"

if [ ! -f "$ROOT_DIR/.env" ]; then
    POSTGRES_USER="todo"
    POSTGRES_DB="todo_db"
    POSTGRES_PASSWORD="$(
        "$PYTHON" -c 'import secrets; print(secrets.token_hex(24))'
    )"

    read -r -p \
        "Redis SSH host [101.43.72.189]: " \
        REDIS_SSH_HOST
    REDIS_SSH_HOST="${REDIS_SSH_HOST:-101.43.72.189}"

    read -r -p \
        "Redis SSH user [ubuntu]: " \
        REDIS_SSH_USER
    REDIS_SSH_USER="${REDIS_SSH_USER:-ubuntu}"

    read -r -p \
        "MySQL host [sh-cdb-im8up7xq.sql.tencentcdb.com]: " \
        SOURCE_MYSQL_HOST
    SOURCE_MYSQL_HOST="${SOURCE_MYSQL_HOST:-sh-cdb-im8up7xq.sql.tencentcdb.com}"

    read -r -s -p "MySQL password: " SOURCE_MYSQL_PASSWORD
    echo

    if [ -z "$SOURCE_MYSQL_PASSWORD" ]; then
        echo "ERROR: MySQL password 不能为空" >&2
        exit 1
    fi

    DATABASE_URL="postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:15432/${POSTGRES_DB}"

    write_env() {
        printf '%s=%q\n' "$1" "$2"
    }

    {
        echo "# Generated by scripts/bootstrap_env.sh"
        echo "# Do not commit this file."
        echo

        write_env POSTGRES_BIND_IP "127.0.0.1"
        write_env POSTGRES_HOST_PORT "15432"
        write_env POSTGRES_USER "$POSTGRES_USER"
        write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
        write_env POSTGRES_DB "$POSTGRES_DB"
        write_env DATABASE_URL "$DATABASE_URL"

        echo
        write_env REDIS_SSH_HOST "$REDIS_SSH_HOST"
        write_env REDIS_SSH_USER "$REDIS_SSH_USER"
        write_env REDIS_LOCAL_PORT "16379"
        write_env REDIS_REMOTE_HOST "127.0.0.1"
        write_env REDIS_REMOTE_PORT "6379"
        write_env REDIS_URL "redis://127.0.0.1:16379/0"

        echo
        write_env SOURCE_MYSQL_HOST "$SOURCE_MYSQL_HOST"
        write_env SOURCE_MYSQL_PORT "63944"
        write_env SOURCE_MYSQL_USER "root"
        write_env SOURCE_MYSQL_PASSWORD "$SOURCE_MYSQL_PASSWORD"
        write_env SOURCE_MYSQL_DATABASE "db.transform.ss"
        write_env SOURCE_MYSQL_TABLE "tiezi_geo_new"
        write_env SOURCE_MYSQL_SSL_ENABLED "true"
        write_env SOURCE_MYSQL_SSL_VERIFY "false"

        echo
        write_env APP_HOST "0.0.0.0"
        write_env APP_PORT "8000"
    } > "$ROOT_DIR/.env"

    chmod 600 "$ROOT_DIR/.env"

    echo "[OK] 已创建 .env"
else
    echo "[OK] .env 已存在，保持不变"
fi

log "准备 Redis SSH Key"

set -a
source "$ROOT_DIR/.env"
set +a

mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

if [ ! -f "$HOME/.ssh/id_ed25519" ]; then
    ssh-keygen \
        -t ed25519 \
        -N "" \
        -f "$HOME/.ssh/id_ed25519"
fi

if ssh \
    -o BatchMode=yes \
    -o ConnectTimeout=5 \
    -o StrictHostKeyChecking=accept-new \
    "${REDIS_SSH_USER}@${REDIS_SSH_HOST}" \
    true 2>/dev/null
then
    echo "[OK] Redis SSH 免密登录可用"
else
    echo "需要安装 SSH 公钥，可能会要求输入一次服务器密码。"

    ssh-copy-id \
        -o StrictHostKeyChecking=accept-new \
        "${REDIS_SSH_USER}@${REDIS_SSH_HOST}"
fi

log "静态检查"

"$PYTHON" -m compileall \
    -q \
    "$ROOT_DIR/app" \
    "$ROOT_DIR/scripts"

echo
echo "========== 环境初始化完成 =========="
echo "虚拟环境：$VENV_DIR"
echo "日常启动：./scripts/dev_up.sh"
